providers = ["node"]

[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl"]

[phases.install]
cmd = "npm install -g corepack@0.24.1 && corepack enable && pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm run railway:build"

[start]
cmd = "pnpm run railway:start"
